config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "albums#index"
  
  match "*path", to: "albums#index", via: :get
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  albumart   :string
#  artist     :string
#  title      :string
#  titlelist  :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  genre_id   :bigint           not null
#
# Indexes
#
#  index_albums_on_genre_id  (genre_id)
#
# Foreign Keys
#
#  fk_rails_...  (genre_id => genres.id)
#
class Album < ApplicationRecord
  belongs_to :genre
  
  def searchStringInLibraryMusicSearch
    "#{title}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Genre < ApplicationRecord
  validates :title, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
    @album = Album.new
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_url, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :artist, :genre_id, :url, :albumart)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genres_url(), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:title)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Title:</strong>
    <%= album.title %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= album.artist %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= album.genre_id %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= album.url %>
  </p>

  <p>
    <strong>Albumart:</strong>
    <%= album.albumart %>
  </p>

</div>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :genre_id, style: "display: block" %>
	<%= form.collection_select(:genre_id, Genre.all, :id, :title, {:prompt => 'Select the Genre'}, :selected => @album.genre_id ) %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :albumart, style: "display: block" %>
    <%= form.text_field :albumart %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Albums</h1>

<div id="albums">
	<table>
		<tr>
			<th>Genre</th>
			<th>Artist</th>
			<th>Album</th>
			<th>Show/Edit/Destroy</th>
			<th>Controls</th>
		</tr>
  	    <% @albums.each do |album| %>
  		<tr>
			<td><%= album.genre.title %></td>
			<td><%= album.artist %></td>
			<td><%= album.title %></td>
			<td><small><%= link_to "Show", album %> | <%= link_to "Edit", edit_album_path(album) %><%= button_to "Delete", album, method: :delete, form: {style: 'display:inline-block;'} %></small></td>
			<td><a href="http://endor.local:5005/3_wohnzimmer/musicsearch/library/album/<%= album.searchStringInLibraryMusicSearch %>">Play</a></td>
		</tr>
  	  	<% end %>

		<%= form_with(model: @album) do |form| %>
		  <% if @album.errors.any? %>
		  	<tr><td colspan=4>
		    <div style="color: red">
		      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

		      <ul> <% @album.errors.each do |error| %> <li><%= error.full_message %></li> <% end %> </ul> </div> </td></tr> <% end %> <tr> <td><%=
		      form.collection_select(:genre_id, Genre.all, :id, :title, {:prompt => 'Select the Genre'}, { :selected => @album.genre_id, :autofocus => ""} ) %></td>
		      <td><%= form.text_field :artist %></td> 
			  <td><%= form.text_field :title %></td> 
			  <td><%= form.submit %></td> </tr>
  
		<% end %>

	</table>
				

</div>
<a href="http://endor.local:5005/3_wohnzimmer/musicsearch/library/album/all+too+soon">Play 'All too soon'</a> | 
<a href="http://endor.local:5005/3_wohnzimmer/musicsearch/library/song/Take+a+Chance+on+me">Play 'Take a Chance on me'</a> | 
<a href="http://endor.local:5005/3_wohnzimmer/musicsearch/library/song/Abba+Mamma+Mia">Play 'Abba Mamma Mia'</a> | 
<a href="http://endor.local:5005/3_wohnzimmer/musicsearch/library/song/Abba+Knowing+Me+Knowing+You">Play 'Knowing Me Knowing You'</a> | 
<a href="http://endor.local:5005/3_wohnzimmer/musicsearch/library/song/Abba+SOS">Play 'S.O.S'</a> | 
<a href="http://endor.local:5005/3_wohnzimmer/musicsearch/library/album/Philipp%20Fankhauser%20%26%20Checkerboard%20Blues%20Band+...with%20a%20Feeling%21">Play '...with a feeling'</a> | <br />
<a href="http://endor.local:5005/3_wohnzimmer/musicsearch/spotify/album/Nirvana+Nevermind">Play Nevermind on Spotify</a> | 

<br /><a href="http://endor.local:5005/3_wohnzimmer/playpause">Play/Pause</a> | <a href="http://endor.local:5005/3_wohnzimmer/volume/+10">Louder</a> | <a href="http://endor.local:5005/3_wohnzimmer/volume/-10"> Leiser</a>
<br /><%= link_to "New album", new_album_path %>
<br /><%= link_to "Genres", genres_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>

<div>
  <%= link_to "Edit this album", edit_album_path(@album) %> |
  <%= link_to "Back to albums", albums_path %>

  <%= button_to "Destroy this album", @album, method: :delete %>
</div>

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
    <p style="display:inline;"><%= genre.title %></p>
	<label><%= button_to "Delete", genre, method: :delete, form: {style: 'display:inline-block;'} %></label>

</div>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Show this genre", @genre %> |
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Genres</h1>

<div id="genres">
  <% @genres.each do |genre| %>
    <%= render genre %>
  <% end %>
</div>

<h3>New genre</h3>

<%= render "form", genre: @genre %>


<%= link_to "New genre", new_genre_path %><br />
<%= link_to "Albums", albums_path %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render "form", genre: @genre %>

<br>

<div>
  <%= link_to "Back to genres", genres_path %>
</div>

app/views/genres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genre %>

<div>
  <%= link_to "Edit this genre", edit_genre_path(@genre) %> |
  <%= link_to "Back to genres", genres_path %>

  <%= button_to "Destroy this genre", @genre, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Analogisierung</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>